#!/usr/bin/env bash
set -euo pipefail

# SPECTRA Hook: Post-Verify Sign Candidate Discovery
#
# Called after a FAIL → FIX → PASS cycle completes. Proposes new Sign
# candidates based on failure patterns WITHOUT mutating guardrails.
#
# Opt-in: Set SPECTRA_SIGN_DISCOVERY=1 in .env or environment to enable.
# Disabled by default — safe to ignore in existing project flows.
#
# Usage: post-verify-learn.sh <task_id> <project_name> <spectra_dir>
#
# Inputs:
#   - .spectra/logs/task-NNN-verify.md (failure report from prior iteration)
#   - lessons JSONL for the project
#
# Output:
#   - .spectra/logs/sign-candidates-NNN.md (proposed candidates with context)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SPECTRA_HOME="${SPECTRA_HOME:-$(dirname "${SCRIPT_DIR}")}"

# ── Feature gate: disabled by default ──
if [[ "${SPECTRA_SIGN_DISCOVERY:-0}" != "1" ]]; then
    exit 0
fi

# ── Parse arguments ──
TASK_ID="${1:-}"
PROJECT_NAME="${2:-}"
SPECTRA_DIR="${3:-.spectra}"

if [[ -z "${TASK_ID}" || -z "${PROJECT_NAME}" ]]; then
    echo "Usage: post-verify-learn.sh <task_id> <project_name> [spectra_dir]" >&2
    exit 1
fi

LOGS_DIR="${SPECTRA_DIR}/logs"
VERIFY_LOG="${LOGS_DIR}/task-${TASK_ID}-verify.md"
CANDIDATES_FILE="${LOGS_DIR}/sign-candidates-${TASK_ID}.md"

# ── Guard: only run after a successful recovery (PASS after prior FAIL) ──
if [[ ! -f "${VERIFY_LOG}" ]]; then
    # No prior failure report — this wasn't a recovery cycle
    exit 0
fi

# Check that the latest verification passed (recovery complete)
LATEST_RESULT=""
if [[ -f "${LOGS_DIR}/task-${TASK_ID}-verify-script.md" ]]; then
    LATEST_RESULT=$(grep -oP 'Result:\*{0,2}\s*\K\S+' "${LOGS_DIR}/task-${TASK_ID}-verify-script.md" | head -1 || true)
fi
if [[ "${LATEST_RESULT}" != "PASS" ]]; then
    # Still failing — not a completed recovery cycle
    exit 0
fi

# ── Extract failure pattern from the verify log ──
FAILURE_TYPE=$(grep -oiP 'Failure Type:\s*\K\S+' "${VERIFY_LOG}" | head -1 || echo "unknown")
FAILURE_DETAIL=$(grep -A3 'Blocking Issues\|FAIL' "${VERIFY_LOG}" | head -5 || echo "")

# ── Source lessons library for fingerprint computation ──
if [[ -f "${SPECTRA_HOME}/lib/loop-lessons.sh" ]]; then
    source "${SPECTRA_HOME}/lib/loop-lessons.sh"
fi

# ── Check if this pattern already has a Sign ──
SIGNS_FILE="${SPECTRA_HOME}/agents/references/signs-taxonomy.md"
if [[ -f "${SIGNS_FILE}" ]]; then
    # If the failure type is already covered by a Sign, skip
    if grep -qi "${FAILURE_TYPE}" "${SIGNS_FILE}" 2>/dev/null; then
        exit 0
    fi
fi

# ── Extract affected files from the task section ──
PLAN_FILE="${SPECTRA_DIR}/plan.md"
AFFECTED_FILES=""
if [[ -f "${PLAN_FILE}" ]]; then
    AFFECTED_FILES=$(sed -n "/^## Task ${TASK_ID}:/,/^## Task /p" "${PLAN_FILE}" | \
        grep -oP '(?:Files:|owns:|touches:)\s*\K.*' | head -3 || true)
fi

# ── Generate candidate proposal ──
TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)

mkdir -p "${LOGS_DIR}"

cat > "${CANDIDATES_FILE}" <<EOF
# Sign Candidate Proposal — Task ${TASK_ID}

> Generated by post-verify-learn.sh after FAIL → FIX → PASS recovery.
> This is a proposal only — guardrails are NOT modified automatically.
> Review and promote via: spectra-promote --fingerprint <fp>

## Recovery Context
- **Task:** ${TASK_ID}
- **Project:** ${PROJECT_NAME}
- **Timestamp:** ${TIMESTAMP}
- **Failure Type:** ${FAILURE_TYPE}
- **Affected Files:** ${AFFECTED_FILES:-unknown}

## Failure Pattern
\`\`\`
${FAILURE_DETAIL}
\`\`\`

## Proposed Sign
- **Category:** ${FAILURE_TYPE}
- **Pattern:** FAIL → FIX → PASS cycle detected on Task ${TASK_ID}
- **Suggested Prevention:** Add pre-build check or guardrail for ${FAILURE_TYPE} patterns
- **Evidence:** ${VERIFY_LOG}

## Next Steps
1. Review this proposal in the context of the project
2. If the pattern is generalizable, promote to a Sign:
   \`spectra-promote --fingerprint "${FAILURE_TYPE}/task-${TASK_ID}" --to SIGN\`
3. If the pattern is project-specific, dismiss:
   \`rm ${CANDIDATES_FILE}\`
EOF

echo "  Sign candidate proposed: ${CANDIDATES_FILE}"
